name: "Issue Sync"
description: "Synchronizes issues between different projects or organizations"
author: hilbigit for syncing issues to another organization and for forgejo adaption (original codebase for syncing to project by paritytech)
branding:
  icon: check-square
  color: green
inputs:
  labels:
    required: false
    description: array of labels required to execute the action. See Readme for input format.
    type: string
  GITHUB_TOKEN:
    required: true
    type: string
  DESTINATION_ORG:
    required: true
    type: string
    description: Name of the organization the issue shall be copied to
  DESTINATION_REPO:
    required: false
    type: string
    description: Name of the repository the issue shall be copied to (defaults to source repo name)
  DESTINATION_TOKEN:
    description: Token with access right to the target organization. Only required if sync to another org is needed / TARGET_ORG is filled (defaults to GITHUB_TOKEN)
    required: false
    type: string
  SYNC_LABELS_DISABLED:
    description: Set to true if labels shall not be copied into target repo (this must be false in case of using forgejo because of api differences, forgejo expects IDs instead of label names!)
    required: false
    type: string
runs:
  using: 'docker'
  image: './Dockerfile'
